"""Downloadable export files: batch storage + HMAC-signed expiring URLs.

Exported files are stored under one directory per export call (a "batch").
Download links carry an HMAC token derived from the MCP API key and a
timestamp, so a plain browser or agent can fetch a file without headers
while the URL remains unforgeable and expires after a configurable TTL.
"""

import hashlib
import hmac
import shutil
import time
import uuid
from pathlib import Path

# Token length (hex chars) — 128 bits of the SHA-256 digest
_TOKEN_CHARS = 32


class FileStore:
    """Filesystem-backed store for downloadable export batches."""

    def __init__(self, root: Path, secret: str, ttl: int):
        self.root = Path(root)
        self.secret = secret
        self.ttl = ttl

    # ── Writing ──────────────────────────────────────────────────────────

    def create_batch(self) -> tuple[str, Path]:
        """Create a fresh batch directory; returns (batch_id, dir)."""
        batch_id = uuid.uuid4().hex
        batch_dir = self.root / batch_id
        batch_dir.mkdir(parents=True, exist_ok=True)
        return batch_id, batch_dir

    # ── URL building / verification ──────────────────────────────────────

    def build_url(self, public_url: str, batch_id: str, filename: str) -> str:
        """Build a signed, expiring download URL for one file."""
        ts = int(time.time())
        token = self._sign(ts, batch_id, filename)
        base = public_url.rstrip("/") if public_url else "/mcp"
        return f"{base}/files/{batch_id}/{filename}?ts={ts}&token={token}"

    def verify(self, batch_id: str, filename: str, ts: int | str, token: str) -> bool:
        """Check a download token: unforgeable and not expired."""
        try:
            ts = int(ts)
        except (TypeError, ValueError):
            return False
        if abs(time.time() - ts) > self.ttl:
            return False
        expected = self._sign(ts, batch_id, filename)
        return hmac.compare_digest(expected, token or "")

    def _sign(self, ts: int, batch_id: str, filename: str) -> str:
        msg = f"{ts}:{batch_id}/{filename}".encode()
        digest = hmac.new(self.secret.encode(), msg, hashlib.sha256).hexdigest()
        return digest[:_TOKEN_CHARS]

    # ── Serving ──────────────────────────────────────────────────────────

    def file_path(self, batch_id: str, filename: str) -> Path | None:
        """Resolve a request to a file path, rejecting path traversal."""
        if not batch_id or not filename:
            return None
        # Batch ids are UUID hex strings generated by this module
        if not all(c in "0123456789abcdef" for c in batch_id) or len(batch_id) != 32:
            return None
        # Filenames are basenames produced by sanitize_filename; any path
        # separator or parent reference here is an attack, not a file
        if "/" in filename or "\\" in filename or ".." in filename:
            return None
        path = self.root / batch_id / filename
        if not path.is_file():
            return None
        return path

    # ── Housekeeping ─────────────────────────────────────────────────────

    def cleanup(self) -> None:
        """Delete batch directories older than the TTL."""
        if not self.root.is_dir():
            return
        cutoff = time.time() - self.ttl
        for batch_dir in self.root.iterdir():
            try:
                if batch_dir.is_dir() and batch_dir.stat().st_mtime < cutoff:
                    shutil.rmtree(batch_dir, ignore_errors=True)
            except OSError:
                continue


_store: FileStore | None = None


def default_store() -> FileStore:
    """The process-wide store, built from the loaded settings on first use."""
    global _store
    if _store is None:
        from mcp_server.config import load_settings

        settings = load_settings()
        _store = FileStore(Path(settings.files_dir), settings.api_key, settings.download_ttl)
    return _store


def set_default_store(store: FileStore) -> None:
    """Install a specific store (used by the HTTP app and tests)."""
    global _store
    _store = store
