"""add_unique_constraint_view_name

Revision ID: 4f11ac803470
Revises: 724b8b1fd5e1
Create Date: 2026-08-06 16:42:51.109336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f11ac803470'
down_revision: Union[str, Sequence[str], None] = '724b8b1fd5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_views_name', 'views', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_views_name', 'views', type_='unique')
    # ### end Alembic commands ###
