"""add content_hash unique constraint to wallet_withdrawals

Revision ID: 70a297ea8ba6
Revises: ade0524d36bb
Create Date: 2026-07-29 18:24:58.458157

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70a297ea8ba6'
down_revision: str | Sequence[str] | None = 'ade0524d36bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column nullable first (existing rows have no hash yet)
    op.add_column(
        "wallet_withdrawals",
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=True,
            comment="SHA-256 hash of business columns for dedup",
        ),
    )

    # Backfill existing rows with unique legacy values to avoid constraint violations
    op.execute(
        sa.text(
            "UPDATE wallet_withdrawals "
            "SET content_hash = 'legacy_' || id::text "
            "WHERE content_hash IS NULL"
        )
    )

    # Now make the column NOT NULL
    op.alter_column("wallet_withdrawals", "content_hash", nullable=False)

    # Add unique constraint for hash-based dedup
    op.create_unique_constraint(
        "uq_wallet_withdrawal_content_hash",
        "wallet_withdrawals",
        ["content_hash"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wallet_withdrawal_content_hash', 'wallet_withdrawals', type_='unique')
    op.drop_column('wallet_withdrawals', 'content_hash')
    # ### end Alembic commands ###
