"""add_visualizations_table

Revision ID: 724b8b1fd5e1
Revises: d8b69a4de309
Create Date: 2026-08-06 15:55:19.764142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '724b8b1fd5e1'
down_revision: Union[str, Sequence[str], None] = 'd8b69a4de309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visualizations',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='可视化名称'),
    sa.Column('view_id', sa.UUID(), nullable=False, comment='关联视图ID'),
    sa.Column('chart_type', sa.String(length=50), nullable=False, comment='图表类型（table/kpi_card/bar/line/pie/scatter）'),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='图表配置（JSON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['view_id'], ['views.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visualizations')
    # ### end Alembic commands ###
