"""add_dashboards_table

Revision ID: 9b719a1765ae
Revises: 5c8f2a91d4e7
Create Date: 2026-08-11 10:32:27.773232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b719a1765ae'
down_revision: Union[str, Sequence[str], None] = '5c8f2a91d4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='仪表盘名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='仪表盘描述'),
    sa.Column('layout_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='布局配置（瓦片对象数组，JSON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_dashboards_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboards')
    # ### end Alembic commands ###
