"""init

Revision ID: a97bfa4a5039
Revises:
Create Date: 2026-07-28 15:43:08.368387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a97bfa4a5039"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="数据源名称"),
        sa.Column("source_type", sa.String(length=50), nullable=False, comment="数据源类型（csv/excel）"),
        sa.Column(
            "config",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="数据源配置（文件路径、分隔符、编码等）",
        ),
        sa.Column("schedule", sa.String(length=100), nullable=True, comment="调度计划（cron表达式，为空表示手动导入）"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refund_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("refund_order_no", sa.String(length=100), nullable=False, comment="退费单号"),
        sa.Column("platform_order_no", sa.String(length=100), nullable=True, comment="平台订单号"),
        sa.Column("third_party_order_no", sa.String(length=100), nullable=True, comment="三方订单号"),
        sa.Column("device_sn", sa.String(length=100), nullable=True, comment="设备SN"),
        sa.Column("refund_reason", sa.String(length=200), nullable=True, comment="退费原因"),
        sa.Column("plan_name", sa.String(length=200), nullable=True, comment="套餐名称"),
        sa.Column("merchant_name", sa.String(length=200), nullable=True, comment="商户名称"),
        sa.Column("refund_amount", sa.Numeric(precision=12, scale=2), nullable=True, comment="退费金额"),
        sa.Column("actual_refund_amount", sa.Numeric(precision=12, scale=2), nullable=True, comment="实退金额"),
        sa.Column("remark", sa.Text(), nullable=True, comment="备注"),
        sa.Column("status", sa.String(length=50), nullable=True, comment="状态"),
        sa.Column("refund_method", sa.String(length=100), nullable=True, comment="退款方式"),
        sa.Column("audit_remark", sa.Text(), nullable=True, comment="审核备注"),
        sa.Column("auditor", sa.String(length=100), nullable=True, comment="审核人"),
        sa.Column("record_created_at", sa.DateTime(), nullable=True, comment="创建时间（原始记录）"),
        sa.Column("record_updated_at", sa.DateTime(), nullable=True, comment="更新时间（原始记录）"),
        sa.Column("operator", sa.String(length=100), nullable=True, comment="操作人"),
        sa.Column("plan_price", sa.Numeric(precision=12, scale=2), nullable=True, comment="套餐价格"),
        sa.Column("imported_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="导入时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refund_order_no"),
    )
    op.create_table(
        "service_refund_work_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("work_order_no", sa.String(length=100), nullable=False, comment="工单号"),
        sa.Column("sn", sa.String(length=100), nullable=True, comment="SN"),
        sa.Column("device_type", sa.String(length=100), nullable=True, comment="设备类型"),
        sa.Column("device_type_remark", sa.Text(), nullable=True, comment="设备类型备注"),
        sa.Column("phone", sa.String(length=50), nullable=True, comment="手机号"),
        sa.Column("service_category", sa.String(length=100), nullable=True, comment="服务类别"),
        sa.Column("service_item", sa.String(length=200), nullable=True, comment="服务项"),
        sa.Column("priority", sa.Integer(), nullable=True, comment="优先级"),
        sa.Column("status", sa.String(length=50), nullable=True, comment="状态"),
        sa.Column("customer_remark", sa.Text(), nullable=True, comment="备注（用户）"),
        sa.Column("registered_at", sa.DateTime(), nullable=True, comment="登记时间"),
        sa.Column("activated_at", sa.DateTime(), nullable=True, comment="激活时间"),
        sa.Column("dispatched_at", sa.DateTime(), nullable=True, comment="分发时间"),
        sa.Column("completed_at", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.Column("processing_duration", sa.Integer(), nullable=True, comment="处理时长"),
        sa.Column("registrar", sa.String(length=100), nullable=True, comment="登记人"),
        sa.Column("channel", sa.String(length=100), nullable=True, comment="录入渠道"),
        sa.Column("processing_node", sa.String(length=100), nullable=True, comment="处理节点"),
        sa.Column("processor", sa.String(length=100), nullable=True, comment="处理人"),
        sa.Column("processing_opinion", sa.Text(), nullable=True, comment="处理意见"),
        sa.Column("is_appeal", sa.String(length=50), nullable=True, comment="是否申诉"),
        sa.Column("order_no", sa.String(length=100), nullable=True, comment="订单编号"),
        sa.Column("bank_name", sa.String(length=200), nullable=True, comment="收款开户行"),
        sa.Column("bank_card_no", sa.String(length=100), nullable=True, comment="银行卡号"),
        sa.Column("recipient", sa.String(length=100), nullable=True, comment="收件人"),
        sa.Column("internal_remark", sa.Text(), nullable=True, comment="备注（内部）"),
        sa.Column("refund_amount", sa.Numeric(precision=12, scale=2), nullable=True, comment="退款金额"),
        sa.Column(
            "estimated_refundable_amount", sa.Numeric(precision=12, scale=2), nullable=True, comment="预估可退金额"
        ),
        sa.Column("imported_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="导入时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_order_no"),
    )
    op.create_table(
        "wallet_withdrawals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("account_id", sa.String(length=100), nullable=True, comment="账户ID"),
        sa.Column("wallet_balance", sa.Numeric(precision=12, scale=2), nullable=True, comment="钱包余额"),
        sa.Column("sn", sa.String(length=100), nullable=True, comment="SN"),
        sa.Column("operation_type", sa.String(length=100), nullable=True, comment="操作类型"),
        sa.Column("operation_amount", sa.Numeric(precision=12, scale=2), nullable=True, comment="操作金额"),
        sa.Column("remark", sa.Text(), nullable=True, comment="备注"),
        sa.Column("operated_at", sa.DateTime(), nullable=True, comment="操作时间"),
        sa.Column("operator", sa.String(length=100), nullable=True, comment="操作人员"),
        sa.Column("imported_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="导入时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("source_id", sa.Integer(), nullable=False, comment="数据源ID"),
        sa.Column(
            "status", sa.String(length=50), nullable=False, comment="导入状态（pending/running/completed/failed）"
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True, comment="开始时间"),
        sa.Column("finished_at", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.Column("row_count", sa.Integer(), nullable=False, comment="导入行数"),
        sa.Column("error_count", sa.Integer(), nullable=False, comment="错误行数"),
        sa.Column("errors", postgresql.JSON(astext_type=sa.Text()), nullable=True, comment="错误详情"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["datasources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("import_jobs")
    op.drop_table("wallet_withdrawals")
    op.drop_table("service_refund_work_orders")
    op.drop_table("refund_orders")
    op.drop_table("datasources")
    # ### end Alembic commands ###
