"""drop wallet_withdrawals composite unique constraint

Revision ID: ade0524d36bb
Revises: 13b09965c2f5
Create Date: 2026-07-29 17:36:21.248580

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ade0524d36bb"
down_revision: str | Sequence[str] | None = "13b09965c2f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "import_jobs",
        "status",
        existing_type=sa.VARCHAR(length=50),
        comment="导入状态(pending/running/completed/failed)",
        existing_comment="导入状态（pending/running/completed/failed）",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_wallet_withdrawal_key"), "wallet_withdrawals", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_wallet_withdrawal_key"),
        "wallet_withdrawals",
        ["account_id", "sn", "operated_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "import_jobs",
        "status",
        existing_type=sa.VARCHAR(length=50),
        comment="导入状态（pending/running/completed/failed）",
        existing_comment="导入状态(pending/running/completed/failed)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
